-- Drop the Track D contractor/dispatch rail (ADR-028, 2026-08-03).
--
-- Track D (contractor directory + dispatch + one-tap WhatsApp + signed job
-- link) moved out of this codebase; active scope is the Checklist app and
-- Network monitoring only. The three tables were EMPTY in production when this
-- was authored (verified 2026-08-03 against ep-summer-cloud: contractors=0,
-- contractor_properties=0, contractor_jobs=0, photos with contractor_job_id=0),
-- so this drops schema, not data.
--
-- Photo goes back to exactly-one-of(response, issue) — see ADR-016.
--
-- ⚠ DEPLOY ORDER: ship the code that no longer references these objects FIRST,
-- then apply this migration. Applying it while the previous build is still live
-- would make every `SELECT` naming contractor_job_id fail.
--
-- Body generated by `prisma migrate diff` against the pre-removal datamodel, so
-- `migrate deploy` leaves no drift.

-- DropForeignKey
ALTER TABLE "photos" DROP CONSTRAINT "photos_contractor_job_id_fkey";
-- DropForeignKey
ALTER TABLE "contractors" DROP CONSTRAINT "contractors_user_id_fkey";
-- DropForeignKey
ALTER TABLE "contractor_properties" DROP CONSTRAINT "contractor_properties_contractor_id_fkey";
-- DropForeignKey
ALTER TABLE "contractor_properties" DROP CONSTRAINT "contractor_properties_property_id_fkey";
-- DropForeignKey
ALTER TABLE "contractor_jobs" DROP CONSTRAINT "contractor_jobs_property_id_fkey";
-- DropForeignKey
ALTER TABLE "contractor_jobs" DROP CONSTRAINT "contractor_jobs_contractor_id_fkey";
-- DropForeignKey
ALTER TABLE "contractor_jobs" DROP CONSTRAINT "contractor_jobs_created_by_user_id_fkey";
-- DropIndex
DROP INDEX "photos_contractor_job_id_idx";
-- AlterTable
ALTER TABLE "photos" DROP COLUMN "contractor_job_id";
-- DropTable
DROP TABLE "contractors";
-- DropTable
DROP TABLE "contractor_properties";
-- DropTable
DROP TABLE "contractor_jobs";
-- DropEnum
DROP TYPE "JobStatus";
-- DropEnum
DROP TYPE "Trade";
